#!/bin/bash

(
  set -e

  echo -e "\n Printing path..."
  ls
  ls gopath

  echo -e "\n Creating archive..."
  version=`cat version/number`
  filename="bosh-softlayer-cpi-release-"
  tar -cvzf "$filename$version" gopath/bosh-softlayer-cpi-release/*
)