---
platform: linux
image: docker:///cloudfoundry/bosh-lite-ci
inputs:
  - name: bosh-cpi-release
  - name: version-semver
  - name: bosh-cli
outputs:
  - name: candidate
run:
  path: bosh-cpi-release/ci/tasks/build-candidate.sh
