---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: bosh-init
  - name: deployment
run:
  path: bosh-cpi-release/ci/tasks/teardown-director.sh
params:
  BOSH_INIT_LOG_LEVEL:        warn