sudo: false
language: go
go:
  - 1.7.1
before_install:
- go get github.com/tools/godep
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/golang/go/src/cmd/vet
- go get github.com/onsi/gomega
install: true
script: bin/ci
branches:
  only:
  - master
