---
name: concourse
director_uuid: REPLACE_ME

releases:
- name: concourse
  version: latest
- name: garden-linux
  version: latest

stemcells:
- alias: default
  name: light-bosh-stemcell-3232.4-softlayer-esxi-ubuntu-trusty-go_agent
  version: 3232.4

instance_groups:
- name: concourse
  instances: 1
  azs: [az1]
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with username/password, or configure GitHub auth
      basic_auth_username: &atc_username REPLACE_ME
      basic_auth_password: &atc_password REPLACE_ME
      postgresql_database: &atc_db atc
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: REPLACE_ME
      publicly_viewable: true
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: REPLACE_ME
        password: REPLACE_ME
  - name: tsa
    release: concourse
    properties:
      forward_host: 127.0.0.1
      atc:
        address: 127.0.0.1:8080
  - name: garden
    release: garden-linux
    properties:
      listen_network: tcp
      listen_address: 0.0.0.0:7777
      allow_host_access: true
      disk_quota_enabled: false
      log_level: debug
  - name: groundcrew
    release: concourse
    properties:
      tsa:
        host: 127.0.0.1
      garden:
        address: 127.0.0.1:7777
  vm_type: concourse-server
  stemcell: default
  persistent_disk_type: small
  networks:
  - name: concourse
  env:
    bosh:
      keep_root_password: true

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 10
